export type SampleRow = {
  id: string;
  drillNum: string;
  sampleNum: string;
  depth: string;
  time: string;
  soilType: string;
  color: string;
  smell: string;
  moisture: string;
  pid: string;
  pid20: string;
  notes: string;
  sendToLab: boolean;
};

export type FieldJournalData = {
  site: string;
  address: string;
  date: string;
  readinessCheck: string;
  drillingTool: string;
  arrivalTime: string;
  tempStart: string;
  endTime: string;
  tempEnd: string;
  sampler1: string;
  sampler2: string;
  client: string;
  clientRep: string;
  pid: string;
  pidOpenAir: string;
  weather: string;
  labCalibValid: string;
  dailyCalib: string;
  coldStorage: string;
  samples: SampleRow[];
  signature: string;
};

export type ChainOfCustodyData = {
  site: string;
  date: string;
  lab: string;
  billedTo: string;
  address: string;
  weather: string;
  landUse: string;
  groundwaterLevel: string;
  pid: string;
  samplerName: string;
  reportApprover: string;
  clientName: string;
  contactPerson: string;
  drilledBySubcontractor: string;
  sampledBySubcontractor: string;
  deviations: string;
  tests: string[];
  storageLocation: string;
  storageManager: string;
  storageStartDate: string;
  storageStartTime: string;
  storageEndDate: string;
  storageEndTime: string;
  storageCondition: string;
  deliveredBy: string;
  deliveryDate: string;
  deliveryTime: string;
  receivedBy: string;
  receivedDate: string;
  receivedTime: string;
  signature: string;
  samples: SampleRow[];
};

export const SOIL_TYPES = ["חרסית", "חרסית שמנה", "חמרה", "לס", "כורכר", "חול", "מצעים", "אחר"];
export const COLORS = ["חום", "שחור", "אדום", "אפור", "לבן", "צהוב", "כתום", "אחר"];
export const MOISTURE = ["יבש", "לח", "רטוב"];
export const SMELL = ["אין", "קל", "חזק"];
export const WEATHER = ["שמשי", "מעונן", "גשום", "רוח חזקה"];
export const DRILLING_TOOLS = ["גר יד", "מקדח", "חפירת בור", "אחר"];
export const SAMPLING_TOOLS = ["צנצנת זכוכית", "לינר", "שקית", "אחר"];
export const LAB_TESTS = ["TPH D+O", "ICP מתכות", "PFAS", "CR+6", "PH", "SVOC", "VOC", "TPH GRO"];
